### ISSUE TITLE
Does not work in pending-log view

### ISSUE THREAD

**Issue by cmartin81** [gregbillings/PT_Tracker_Graph#2]
Great js addon!
But it does not work in pending-log view.

**Comment by sokol815** [comment]
Please ensure you're using the latest version. As of 3 hours ago, it does.

**Comment by cmartin81** [comment]
Thanks! It works!

**Comment by cmartin81** [comment]
I had a version from 10 hours ago..

**Comment by sokol815** [comment]
Good to hear. Thanks for following up.
