### ISSUE TITLE
Stopped working with PT

### ISSUE THREAD

**Issue by aktrader87** [gregbillings/PT_Tracker_Graph#5]
I tried to update profit trailer and the script seems to not work any more

**Comment by orangebutblue** [comment]
strangely, the graphs still work correctly in one of my chrome-instances - but not in the other.

same pc - same browser - same version - same extension (tampermonkey) - same graphs-code - just different chrome-users

**Comment by sokol815** [comment]
could you pop open the dev tools (F12 on a PC) and refresh the page then post here the errors you're seeing?

Thanks.

**Comment by sokol815** [comment]
I just updated profit trailer to .19... no issues on my side. Please send me the errors you're getting.

**Comment by orangebutblue** [comment]
I get a bunch of these errors:
GTOBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 ETHBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 LSKBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 BCCBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 POEBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 VIBEBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 XMRBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 MODBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 MTLBTC is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 GTOBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 ETHBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 LSKBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 POEBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 VIBEBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 XMRBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 MODBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 MTLBTC is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 GTOBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 ETHBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 LSKBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 POEBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 XVGBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 VIBEBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 XMRBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 MODBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 MTLBTC is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 GTOBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 ETHBTC_PBL is signaling a hang.
userscript.html?id=4a575bc0-5eda-4da4-a66a-eeca33a86acb:315 LSKBTC_PBL is signaling a hang.

**Comment by orangebutblue** [comment]
I think I figured out the problem....

the graph-addon clashes with the "all-in-one" addon:
https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Web-GUI-Addons/All-In-One

**Comment by sokol815** [comment]
@orangebutblue that makes perfect sense... both addons contain this code. =) just use the all-in-one addon.
